<?php
/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 on 06/17/2016
 */

namespace MagicTelecomAPILib;

class Configuration {
    //The base Uri for API calls
    public static $BASEURI = 'http://sandbox.api.magictelecom.com';

    //The API Token for authentication
    public static $APITOKEN = '21549887ebe86ec500873a745ce136902d83ebc9';

}
